name: ScreenDL

hyper:
  epochs: 100
  batch_size: 256
  learning_rate: 0.0001

  activation: leaky_relu
  use_dropout: false
  use_batch_norm: false
  use_l2: false
  use_noise: true
  dropout_rate: 0.0
  noise_stddev: 0.3
  l2_factor: 1e-4
  weight_decay: 1e-4

  early_stopping: true

  hidden_dims:
    exp: [512, 256, 128, 64]
    cnv: [512, 256, 128, 64]
    mut: [512, 256, 128, 64]
    mol: [256, 128, 64]
    ont: []
    shared: [128, 64]

feat:
  use_mut: false
  use_cnv: false
  use_ont: false
  use_mr: false

io:
  save: false
  tensorboard: false