"""Constants for visualization."""

DRUG_TO_PATHWAY_EXT = {
    "4mu8C": "Other",  # targets IRE1 RNase which is involved in the unfolded protein response
    "A-966492": "Genome integrity",
    "Abemaciclib": "Cell cycle",
    "AMG232": "p53 pathway",
    "APG1387": "Apoptosis regulation",
    "ASLAN-002": "RTK signaling",
    "AZD0156": "Genome integrity",
    "AZD4573": "Cell cycle",
    "AZD5363": "PI3K/MTOR signaling",
    "Berzosertib": "Genome integrity",
    "Birinapant": "Apoptosis regulation",
    "Carboplatin": "DNA replication",
    "Ceritinib": "RTK signaling",
    "Cobimetinib": "ERK MAPK signaling",
    "Copanlisib": "PI3K/MTOR signaling",
    "Crenigacestat": "Other",
    "Emavusertib": "Other, kinases",
    "Endoxifen": "Hormone-related",
    "Enzalutamide": "Hormone-related",
    "Epacadostat": "Metabolism",
    "EPZ011989": "Chromatin histone methylation",
    "Erdafitinib": "RTK signaling",
    "Eribulin": "Mitosis",
    "Everolimus": "PI3K/MTOR signaling",
    "GDC-0152": "Apoptosis regulation",
    "GDC-0917": "Apoptosis regulation",
    "Ixazomib": "Protein stability and degradation",
    "Megestrol Acetate": "Hormone-related",
    "Methoxyamine": "DNA replication",
    "MIK665": "Apoptosis regulation",
    "Nedisertib": "Genome integrity",
    "Neratinib": "EGFR/HER2 signaling",  # could also be RTK signaling (HER2/ERBB2 and EGFR)
    "Onalespib": "Protein stability and degradation",
    "ONC206": "Other, kinases",
    "Pamiparib": "Genome integrity",
    "Pelcitoclax": "Apoptosis regulation",
    "Pevonedistat": "Genome integrity",
    "RO4929097": "WNT signaling",
    "Sapanisertib": "PI3K/MTOR signaling",
    "Selinexor": "Other",
    "Sotorasib": "ERK MAPK signaling",
    "TAK-243": "Protein stability and degradation",
    "Telaglenastat": "Other",
    "Tivantinib": "RTK signaling",
    "Tolinapant": "Apoptosis regulation",
    "Triapine": "DNA replication",
    "Tucatinib": "EGFR/HER2 signaling",
    "Vemurafenib": "ERK MAPK signaling",
    "ZW4864": "WNT signaling",
}


FIXED_DRUG_NAMES = {
    "MK-1775": "Adavosertib",
    "AZD5363": "Capivasertib",
    "VE-822": "Berzosertib",
    "EPZ5676": "Pinometostat",
}
