defaults:
  - _self_
  - dataset: CellModelPassportsGDSCv2
  - model: ScreenDL
  - override hydra/sweeper: optuna

hydra:
  run:
    dir: /scratch/ucgd/lustre-work/marth/u0871891/datastore/outputs/hparams/${dataset.name}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: /scratch/ucgd/lustre-work/marth/u0871891/datastore/outputs/hparams/${dataset.name}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: test
    storage: null
    n_trials: 500
    n_jobs: 1
    params:
      model.hyper.batch_size: choice(128, 256, 512, 1024)
      model.hyper.learning_rate: tag(log, interval(0.00001, 0.001))
      model.hyper.use_batch_norm: choice(true, false)
      model.hyper.use_dropout: true
      model.hyper.dropout_rate: choice(0.0, 0.1, 0.2, 0.3, 0.4, 0.5)
      model.hyper.activation: leaky_relu

output:
  log: logs
  