defaults:
  - _self_
  - dataset: CellModelPassportsGDSCv2AUC
  - model: ScreenDL
  - override hydra/sweeper: optuna

hydra:
  run:
    dir: /scratch/ucgd/lustre-work/marth/u0871891/datastore/outputs/hparams/${dataset.name}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: /scratch/ucgd/lustre-work/marth/u0871891/datastore/outputs/hparams/${dataset.name}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: test
    storage: null
    n_trials: 300
    n_jobs: 1
    params:
      model.hyper.hidden_dims.exp: choice([512, 256, 128, 64], [1024, 512, 256, 128])
      model.hyper.hidden_dims.mol: choice([256, 128, 64], [128, 64, 32])
      model.hyper.hidden_dims.shared: choice([64, 32], [64, 32, 16])
      model.hyper.batch_size: choice(128, 256, 512)
      model.hyper.learning_rate: tag(log, interval(0.00005, 0.0005))
      model.hyper.use_batch_norm: false
      model.hyper.use_dropout: false
      model.hyper.activation: choice(leaky_relu, relu)
      model.hyper.use_noise: true
      model.hyper.noise_stddev: range(0.0, 0.4, step=0.05)

output:
  log: logs