defaults:
  - _self_
  - dataset: CellModelPassports-GDSCv1v2-HCI
  - model: ScreenDL

_datastore_: ${hydra:runtime.cwd}/data
_experiment_: ${_datastore_}/outputs/experiments/pdx_validation

hydra:
  run:
    dir: ${_experiment_}/${dataset.name}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: ${_experiment_}/${dataset.name}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  sweeper:
    params:
      dataset.split.id: 1,2,3,4,5,6,7,8,9,10

xfer:
  hyper:
    epochs: 30
    batch_size: 256
    learning_rate: 1e-4
    weight_decay: 1e-2
    frozen_layer_prefixes: null
    frozen_layer_names:
      - exp_mlp_1
      - mol_mlp_1
      - mol_mlp_2

screenahead:
  opt:
    seed: 1771
    n_drugs: 12
    na_thresh: null
    selector: principal
    exclude_drugs: null
    mode: screen-selected # screen-all or screen-selected
  hyper:
    learning_rate: 1e-4
    batch_size: null
    epochs: 20
    frozen_layer_prefixes:
      - mol
      - exp
    frozen_layer_names: null

experiment:
  pdx_obs_path: ${_datastore_}/pdx/pdx_clinical_response.csv
  pdx_ids: null
  keep_pdmc_only_drugs: all
  min_pdmcs_per_drug: 20
  background_correction: false

output:
  log: logs