defaults:
  - _self_
  - dataset: CellModelPassports-GDSCv1v2-HCI
  - model: ScreenDL

_datastore_: /scratch/ucgd/lustre-labs/marth/scratch/u0871891/datastore
_experiment_: ${_datastore_}/outputs/experiments/pdxo_validation

hydra:
  run:
    dir: ${_experiment_}/${dataset.name}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: ${_experiment_}/${dataset.name}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  sweeper:
    params:
      dataset.split.id: 1,2,3,4,5,6,7,8,9,10

xfer:
  hyper:
    epochs: 30
    batch_size: 256
    learning_rate: 1e-4
    weight_decay: 1e-2
    frozen_layer_prefixes:
      - mol
    frozen_layer_names:
      - exp_mlp_1

screenahead:
  opt:
    seed: 1771
    n_drugs: 12
    selector: principal
    exclude_drugs: null
  hyper:
    learning_rate: 1e-4
    batch_size: null
    epochs: 20
    frozen_layer_prefixes:
      - mol
      - exp
    frozen_layer_names: null

experiment:
  min_pdmcs_per_drug: 8
  keep_pdmc_only_drugs: all

output:
  log: logs