defaults:
  - _self_
  - dataset: CellModelPassportsGDSCv1v2Hallmark
  - model: ScreenDL

hydra:
  run:
    dir: /scratch/ucgd/lustre-work/marth/u0871891/datastore/outputs/screenahead/${dataset.name}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: /scratch/ucgd/lustre-work/marth/u0871891/datastore/outputs/screenahead/${dataset.name}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  sweeper:
    params:
      dataset.split.id: 1,2,3,4,5,6,7,8,9,10

screenahead:
  opt:
    seed: 1771
    n_drugs: 20
    selector: principal
  hyper:
    learning_rate: 0.0001
    batch_size: 32
    epochs: 20
  io:
    predict_all: false

output:
  log: logs