defaults:
  - dataset: CellModelPassports-GDSCv1v2
  - model: ScreenDL
  - _self_

_datastore_: ${hydra:runtime.cwd}/data
_experiment_: ${_datastore_}/outputs/experiments/screenahead_related_drugs

hydra:
  run:
    dir: ${_experiment_}/${dataset.name}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: ${_experiment_}/${dataset.name}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  sweeper:
    params:
      dataset.split.id: 1,2,3,4,5,6,7,8,9,10

screenahead:
  opt:
    seed: 1771
    n_drugs: 20
    max_best_drugs: 10
  hyper:
    learning_rate: 0.0001
    batch_size: 32
    epochs: 20

experiment:
  drug_id: "5-Fluorouracil"

output:
  log: logs