defaults:
  - dataset: CellModelPassports-GDSCv1v2
  - model: ScreenDL
  - _self_

_datastore_: ${hydra:runtime.cwd}/data
_experiment_: ${_datastore_}/outputs/experiments/screenahead_drug_selection

hydra:
  run:
    dir: ${_experiment_}/${dataset.name}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: ${_experiment_}/${dataset.name}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  sweeper:
    params:
      dataset.split.id: 1,2,3,4,5,6,7,8,9,10

screenahead:
  opt:
    seed: 1771
    n_drugs: [5, 10, 15, 20, 25]
    selectors:
      - uniform
      - agglomerative
      - doptimal
      - principal
      - random
  hyper:
    learning_rate: 0.0001
    batch_size: 32
    epochs: 20

output:
  log: logs