defaults:
  - _self_
  - dataset: CellModelPassports-GDSCv1v2
  - model: ScreenDL

_datastore_: /scratch/ucgd/lustre-labs/marth/scratch/u0871891/datastore
_experiment_: ${_datastore_}/outputs/experiments/screenahead_gds_compare

hydra:
  run:
    dir: ${_experiment_}/${dataset.name}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: ${_experiment_}/${dataset.name}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  sweeper:
    params:
      dataset.split.id: 1,2,3,4,5,6,7,8,9,10

screenahead:
  opt:
    seed: 1771
    n_drugs: 20
    selector: principal
  hyper:
    learning_rate: 0.0001
    batch_size: 32
    epochs: 20
  io:
    predict_all: false

output:
  log: logs