defaults:
  - dataset: CellModelPassportsGDSCv2HCIExpressionOnly
  - model: ScreenDL
  - _self_

hydra:
  run:
    dir: /scratch/ucgd/lustre-work/marth/u0871891/datastore/outputs/experiments/pdmc_xfer/${dataset.name}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: /scratch/ucgd/lustre-work/marth/u0871891/datastore/outputs/experiments/pdmc_xfer/${dataset.name}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  sweeper:
    params:
      dataset.split.id: 1,2,3,4,5,6,7,8,9,10

xfer:
  hyper:
    epochs: 10
    batch_size: 256
    learning_rate: 1e-4
    weight_decay: null

screenahead:
  opt:
    seed: 1771
    n_drugs: 10
    selector: principal
  hyper:
    learning_rate: 1e-4
    batch_size: null
    epochs: 20

experiment:
  run_xfer: true
  run_no_xfer_screenahead: false

output:
  log: logs