tumor_id: BCM15163
base_model: ScreenDL-FT

# options
seed: 1771
n_drugs: 12
na_thresh: null
selector: principal
exclude_drugs: null

# hparams
epochs: 20
batch_size: null
learning_rate: 1e-4
frozen_layer_prefixes:
  - exp
  - mol
frozen_layer_names: null
weight_decay: null
